### ISSUE TITLE
Deploy section: Add DigitalOcean App Platform and Render example

### ISSUE THREAD

**Issue by JeysonFlores** [graphul-rs/graphul-rs.github.io#4]
Hello people. I just saw that this project is getting a little bit of charm so I wanted to provide the following examples for deploying a Graphul project in both [DigitalOcean's App Platform](https://www.digitalocean.com/products/app-platform) (using Docker) and [Render](https://render.com/) (using the default Rust runtime).

These two examples are based on the quill toy project. See [https;//github.com/JeysonFlores/quill](https;//github.com/JeysonFlores/quill).

## DigitalOcean App Platform
DO App Platform currently does not support Rust in its set of supported runtimes but they support any project that can be ran inside a docker container. As seen in the quill project, with the following source code as example:

```Rust
use graphul::{Graphul, http::Methods};


#[tokio::main]
async fn main() {
    let mut app = Graphul::new();

    app.get("/", || async {
        "Hello from DigitalOcean 👋!"
    });

    app.run("0.0.0.0:8080").await;
}
```
and this Dockerfile considering `myproject` is the name of your project (and thus, the name of the binary as well)
```Dockerfile
FROM rust:1.67-slim-buster as build

# create a new empty shell project
RUN USER=root cargo new --bin myproject
WORKDIR /myproject

# copy over your manifests
COPY ./Cargo.lock ./Cargo.lock
COPY ./Cargo.toml ./Cargo.toml

# this build step will cache your dependencies
RUN cargo build --release
RUN rm src/*.rs

# copy your source tree
COPY ./src ./src

# build for release
RUN rm ./target/release/deps/myproject*
RUN cargo build --release

# our final base
FROM rust:1.67-slim-buster

# copy the build artifact from the build stage
COPY --from=build /myproject/target/release/myproject .

# set the startup command to run your binary
CMD ["./myproject"]
```

#### Screenshot examples

![do1-edit](https://user-images.githubusercontent.com/68255757/218638118-ccbccf53-1f09-48aa-bfd9-d28c339b1691.png)

![do2-edit](https://user-images.githubusercontent.com/68255757/218638161-cfbe4350-be51-4cad-83c5-4dfa0527e6be.png)

![do3-edit](https://user-images.githubusercontent.com/68255757/218638172-5bb24c90-676c-44fe-b969-c02f98447d51.png)

## Render
Render do support Rust in its runtimes stack, making the process of deploying a Graphul app a straight-forward experience.
It does not require any special configuration file, env file, dockerfile, etc. You just need to provide the repo of your project, and set the build & run commands.
#### Screenshot examples

![re1-edit](https://user-images.githubusercontent.com/68255757/218638653-84d73e7d-9d1b-41d7-95e6-aad6eaabf888.png)
![re2-edit](https://user-images.githubusercontent.com/68255757/218638661-65f0f64a-b791-40e3-9dda-a30a39122eac.jpg)
![re3-edit](https://user-images.githubusercontent.com/68255757/218638681-c71a9383-a68f-4979-a264-a6e4a71c4865.jpg)
![re4-edit](https://user-images.githubusercontent.com/68255757/218638690-4c9fb00c-e718-4ea0-bb2f-9d0785f90d25.png)

### Conclusion
I hope these examples and the repo of [JeysonFlores/quill](https://github.com/JeysonFlores/quill) can be helpful to extend the documentation.
These examples are the result of a set of tests using different cloud providers to deploy a Graphul app. I hope to expand this list soon with other interesting cloud providers like [Railway](https://railway.app/) or [Fly.io
](https://fly.io/). Thanks

**Comment by Phosphorus-M** [comment]
Hi Jeyson, great job, perfectly this could be in the documentation, with reference links and all!
Would you prefer to make a pull request or would you prefer me to do it?
I wouldn't mind at all doing it myself but maybe you do the commit.

Whatever your decision thanks for contributing, you are the first to write something!

**Comment by JeysonFlores** [comment]
I can write it myself if you agree. I opened this issue to see if it could be accepted as part of the docs. In a few days I'll open the PR!
